Sitegeist:
  Neos:
    SymfonyMailer:
      dsn: '%env:MAILER_DSN%'
  StoneTablet:
    defaultExcludedFields:
      - corpusDelicti
      - errareHumanumEst
      - time

Litefyr:
  PaperTiger:
    subject: 'Formular auf der Seite {documentLabel} wurde ausgefüllt'
    sender:
      address: '%env:MAILER_FROM%'
      name: 'Website {currentSiteName}'

Neos:
  Neos:
    fusion:
      autoInclude:
        Litefyr.PaperTiger: true
    userInterface:
      translation:
        autoInclude:
          Litefyr.PaperTiger:
            - 'NodeTypes/*'
